#!/bin/bash

#this script need to run with root privilliages to install jenkins

apt update -y

apt-cache search openjdk | grep 17

apt install openjdk-17-jdk

apt install openjdk-17-jre

wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

apt-get update -y

apt-get install jenkins -y

systemctl enable jenkins

systemctl start jenkins

echo "this is the passcode"

cat /var/lib/jenkins/secrets/initialAdminPassword
